/**
 * The single-stock screening universe: liquid, large-cap US names a swing
 * trader would actually put through Stage 1.
 *
 * This is the equity counterpart to the ETF table in `instruments.ts`. Where
 * that table maps a *direction* to an expression vehicle, this one is a flat
 * screening list — each name is a candidate the screener resolves and ranks
 * directly. Only genuinely liquid names belong here (roughly the §1 floor of
 * $5M average daily dollar volume), so a fill assumption never becomes fiction.
 *
 * `sector` is one of the 11 GICS strings. The first eight line up with the
 * sector ETF exposures already in `instruments.ts`; COMMUNICATION, MATERIALS
 * and REAL_ESTATE round the set out to the full GICS taxonomy.
 */

export interface StockDef {
  readonly symbol: string;
  readonly name: string;
  /** One of the 11 GICS sectors. */
  readonly sector: string;
}

export const STOCK_UNIVERSE: readonly StockDef[] = [
  // ---- Technology -----------------------------------------------------
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'TECH' },
  { symbol: 'MSFT', name: 'Microsoft Corp.', sector: 'TECH' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', sector: 'TECH' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'TECH' },
  { symbol: 'ORCL', name: 'Oracle Corp.', sector: 'TECH' },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'TECH' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'TECH' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', sector: 'TECH' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', sector: 'TECH' },
  { symbol: 'ACN', name: 'Accenture plc', sector: 'TECH' },
  { symbol: 'IBM', name: 'International Business Machines Corp.', sector: 'TECH' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.', sector: 'TECH' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'TECH' },
  { symbol: 'INTU', name: 'Intuit Inc.', sector: 'TECH' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'TECH' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', sector: 'TECH' },
  { symbol: 'MU', name: 'Micron Technology Inc.', sector: 'TECH' },
  { symbol: 'ADI', name: 'Analog Devices Inc.', sector: 'TECH' },
  { symbol: 'LRCX', name: 'Lam Research Corp.', sector: 'TECH' },
  { symbol: 'KLAC', name: 'KLA Corp.', sector: 'TECH' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.', sector: 'TECH' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', sector: 'TECH' },
  { symbol: 'ASML', name: 'ASML Holding N.V.', sector: 'TECH' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor Manufacturing Co. Ltd.', sector: 'TECH' },
  { symbol: 'ARM', name: 'Arm Holdings plc', sector: 'TECH' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.', sector: 'TECH' },
  { symbol: 'ON', name: 'ON Semiconductor Corp.', sector: 'TECH' },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.', sector: 'TECH' },
  { symbol: 'MCHP', name: 'Microchip Technology Inc.', sector: 'TECH' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems Inc.', sector: 'TECH' },
  { symbol: 'GFS', name: 'GlobalFoundries Inc.', sector: 'TECH' },
  { symbol: 'SWKS', name: 'Skyworks Solutions Inc.', sector: 'TECH' },
  { symbol: 'QRVO', name: 'Qorvo Inc.', sector: 'TECH' },
  { symbol: 'TER', name: 'Teradyne Inc.', sector: 'TECH' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc.', sector: 'TECH' },
  { symbol: 'DELL', name: 'Dell Technologies Inc.', sector: 'TECH' },
  { symbol: 'ANET', name: 'Arista Networks Inc.', sector: 'TECH' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.', sector: 'TECH' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'TECH' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.', sector: 'TECH' },
  { symbol: 'APP', name: 'AppLovin Corp.', sector: 'TECH' },
  { symbol: 'SNOW', name: 'Snowflake Inc.', sector: 'TECH' },
  { symbol: 'DDOG', name: 'Datadog Inc.', sector: 'TECH' },
  { symbol: 'NET', name: 'Cloudflare Inc.', sector: 'TECH' },
  { symbol: 'MDB', name: 'MongoDB Inc.', sector: 'TECH' },
  { symbol: 'ZS', name: 'Zscaler Inc.', sector: 'TECH' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', sector: 'TECH' },
  { symbol: 'WDAY', name: 'Workday Inc.', sector: 'TECH' },
  { symbol: 'TEAM', name: 'Atlassian Corp.', sector: 'TECH' },
  { symbol: 'HUBS', name: 'HubSpot Inc.', sector: 'TECH' },
  { symbol: 'S', name: 'SentinelOne Inc.', sector: 'TECH' },
  { symbol: 'GTLB', name: 'GitLab Inc.', sector: 'TECH' },
  { symbol: 'FSLR', name: 'First Solar Inc.', sector: 'TECH' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc.', sector: 'TECH' },
  { symbol: 'ALAB', name: 'Astera Labs Inc.', sector: 'TECH' },
  { symbol: 'CRWV', name: 'CoreWeave Inc.', sector: 'TECH' },
  { symbol: 'COHR', name: 'Coherent Corp.', sector: 'TECH' },

  // ---- Financials -----------------------------------------------------
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'FINANCIALS' },
  { symbol: 'BAC', name: 'Bank of America Corp.', sector: 'FINANCIALS' },
  { symbol: 'WFC', name: 'Wells Fargo & Co.', sector: 'FINANCIALS' },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc.', sector: 'FINANCIALS' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'FINANCIALS' },
  { symbol: 'BRKB', name: 'Berkshire Hathaway Inc. Class B', sector: 'FINANCIALS' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'FINANCIALS' },
  { symbol: 'MA', name: 'Mastercard Inc.', sector: 'FINANCIALS' },
  { symbol: 'AXP', name: 'American Express Co.', sector: 'FINANCIALS' },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'FINANCIALS' },
  { symbol: 'SCHW', name: 'Charles Schwab Corp.', sector: 'FINANCIALS' },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'FINANCIALS' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'FINANCIALS' },
  { symbol: 'COF', name: 'Capital One Financial Corp.', sector: 'FINANCIALS' },
  { symbol: 'ICE', name: 'Intercontinental Exchange Inc.', sector: 'FINANCIALS' },
  { symbol: 'CME', name: 'CME Group Inc.', sector: 'FINANCIALS' },
  { symbol: 'KKR', name: 'KKR & Co. Inc.', sector: 'FINANCIALS' },
  { symbol: 'BX', name: 'Blackstone Inc.', sector: 'FINANCIALS' },
  { symbol: 'APO', name: 'Apollo Global Management Inc.', sector: 'FINANCIALS' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.', sector: 'FINANCIALS' },
  { symbol: 'XYZ', name: 'Block Inc.', sector: 'FINANCIALS' },
  { symbol: 'COIN', name: 'Coinbase Global Inc.', sector: 'FINANCIALS' },
  { symbol: 'HOOD', name: 'Robinhood Markets Inc.', sector: 'FINANCIALS' },
  { symbol: 'SOFI', name: 'SoFi Technologies Inc.', sector: 'FINANCIALS' },
  { symbol: 'AFRM', name: 'Affirm Holdings Inc.', sector: 'FINANCIALS' },
  { symbol: 'UPST', name: 'Upstart Holdings Inc.', sector: 'FINANCIALS' },
  { symbol: 'NU', name: 'Nu Holdings Ltd.', sector: 'FINANCIALS' },

  // ---- Health Care ----------------------------------------------------
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.', sector: 'HEALTHCARE' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'HEALTHCARE' },
  { symbol: 'LLY', name: 'Eli Lilly & Co.', sector: 'HEALTHCARE' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'HEALTHCARE' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', sector: 'HEALTHCARE' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'HEALTHCARE' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.', sector: 'HEALTHCARE' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'HEALTHCARE' },
  { symbol: 'DHR', name: 'Danaher Corp.', sector: 'HEALTHCARE' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Co.', sector: 'HEALTHCARE' },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'HEALTHCARE' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', sector: 'HEALTHCARE' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', sector: 'HEALTHCARE' },
  { symbol: 'NVO', name: 'Novo Nordisk A/S', sector: 'HEALTHCARE' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.', sector: 'HEALTHCARE' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.', sector: 'HEALTHCARE' },
  { symbol: 'MRNA', name: 'Moderna Inc.', sector: 'HEALTHCARE' },
  { symbol: 'BIIB', name: 'Biogen Inc.', sector: 'HEALTHCARE' },
  { symbol: 'ALNY', name: 'Alnylam Pharmaceuticals Inc.', sector: 'HEALTHCARE' },
  { symbol: 'NBIX', name: 'Neurocrine Biosciences Inc.', sector: 'HEALTHCARE' },
  { symbol: 'ELV', name: 'Elevance Health Inc.', sector: 'HEALTHCARE' },
  { symbol: 'CI', name: 'Cigna Group', sector: 'HEALTHCARE' },
  { symbol: 'CVS', name: 'CVS Health Corp.', sector: 'HEALTHCARE' },
  { symbol: 'HCA', name: 'HCA Healthcare Inc.', sector: 'HEALTHCARE' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', sector: 'HEALTHCARE' },
  { symbol: 'BSX', name: 'Boston Scientific Corp.', sector: 'HEALTHCARE' },
  { symbol: 'MDT', name: 'Medtronic plc', sector: 'HEALTHCARE' },
  { symbol: 'SYK', name: 'Stryker Corp.', sector: 'HEALTHCARE' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corp.', sector: 'HEALTHCARE' },
  { symbol: 'DXCM', name: 'DexCom Inc.', sector: 'HEALTHCARE' },
  { symbol: 'GEHC', name: 'GE HealthCare Technologies Inc.', sector: 'HEALTHCARE' },
  { symbol: 'HIMS', name: 'Hims & Hers Health Inc.', sector: 'HEALTHCARE' },

  // ---- Energy ---------------------------------------------------------
  { symbol: 'XOM', name: 'Exxon Mobil Corp.', sector: 'ENERGY' },
  { symbol: 'CVX', name: 'Chevron Corp.', sector: 'ENERGY' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'ENERGY' },
  { symbol: 'SLB', name: 'SLB (Schlumberger Ltd.)', sector: 'ENERGY' },
  { symbol: 'EOG', name: 'EOG Resources Inc.', sector: 'ENERGY' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corp.', sector: 'ENERGY' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'ENERGY' },
  { symbol: 'VLO', name: 'Valero Energy Corp.', sector: 'ENERGY' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corp.', sector: 'ENERGY' },
  { symbol: 'DVN', name: 'Devon Energy Corp.', sector: 'ENERGY' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc.', sector: 'ENERGY' },
  { symbol: 'HAL', name: 'Halliburton Co.', sector: 'ENERGY' },
  { symbol: 'BKR', name: 'Baker Hughes Co.', sector: 'ENERGY' },
  { symbol: 'APA', name: 'APA Corp.', sector: 'ENERGY' },
  { symbol: 'CTRA', name: 'Coterra Energy Inc.', sector: 'ENERGY' },
  { symbol: 'LNG', name: 'Cheniere Energy Inc.', sector: 'ENERGY' },

  // ---- Industrials ----------------------------------------------------
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'HON', name: 'Honeywell International Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'INDUSTRIALS' },
  { symbol: 'BA', name: 'Boeing Co.', sector: 'INDUSTRIALS' },
  { symbol: 'UPS', name: 'United Parcel Service Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'RTX', name: 'RTX Corp.', sector: 'INDUSTRIALS' },
  { symbol: 'UNP', name: 'Union Pacific Corp.', sector: 'INDUSTRIALS' },
  { symbol: 'DE', name: 'Deere & Co.', sector: 'INDUSTRIALS' },
  { symbol: 'LMT', name: 'Lockheed Martin Corp.', sector: 'INDUSTRIALS' },
  { symbol: 'GD', name: 'General Dynamics Corp.', sector: 'INDUSTRIALS' },
  { symbol: 'ETN', name: 'Eaton Corp. plc', sector: 'INDUSTRIALS' },
  { symbol: 'GEV', name: 'GE Vernova Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'VRT', name: 'Vertiv Holdings Co.', sector: 'INDUSTRIALS' },
  { symbol: 'PWR', name: 'Quanta Services Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'AXON', name: 'Axon Enterprise Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'URI', name: 'United Rentals Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'HWM', name: 'Howmet Aerospace Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'CARR', name: 'Carrier Global Corp.', sector: 'INDUSTRIALS' },
  { symbol: 'TT', name: 'Trane Technologies plc', sector: 'INDUSTRIALS' },
  { symbol: 'EMR', name: 'Emerson Electric Co.', sector: 'INDUSTRIALS' },
  { symbol: 'FDX', name: 'FedEx Corp.', sector: 'INDUSTRIALS' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.', sector: 'INDUSTRIALS' },
  { symbol: 'LYFT', name: 'Lyft Inc.', sector: 'INDUSTRIALS' },

  // ---- Consumer Discretionary -----------------------------------------
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'HD', name: 'Home Depot Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'MCD', name: "McDonald's Corp.", sector: 'DISCRETIONARY' },
  { symbol: 'NKE', name: 'Nike Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'LOW', name: "Lowe's Companies Inc.", sector: 'DISCRETIONARY' },
  { symbol: 'SBUX', name: 'Starbucks Corp.', sector: 'DISCRETIONARY' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'TJX', name: 'TJX Companies Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'GM', name: 'General Motors Co.', sector: 'DISCRETIONARY' },
  { symbol: 'MAR', name: 'Marriott International Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'SHOP', name: 'Shopify Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'DASH', name: 'DoorDash Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'RBLX', name: 'Roblox Corp.', sector: 'DISCRETIONARY' },
  { symbol: 'DKNG', name: 'DraftKings Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'CVNA', name: 'Carvana Co.', sector: 'DISCRETIONARY' },
  { symbol: 'RIVN', name: 'Rivian Automotive Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'LCID', name: 'Lucid Group Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'F', name: 'Ford Motor Co.', sector: 'DISCRETIONARY' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line Holdings Ltd.', sector: 'DISCRETIONARY' },
  { symbol: 'CCL', name: 'Carnival Corp.', sector: 'DISCRETIONARY' },
  { symbol: 'RCL', name: 'Royal Caribbean Cruises Ltd.', sector: 'DISCRETIONARY' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'DECK', name: 'Deckers Outdoor Corp.', sector: 'DISCRETIONARY' },
  { symbol: 'RH', name: 'RH', sector: 'DISCRETIONARY' },
  { symbol: 'WYNN', name: 'Wynn Resorts Ltd.', sector: 'DISCRETIONARY' },
  { symbol: 'MGM', name: 'MGM Resorts International', sector: 'DISCRETIONARY' },
  { symbol: 'ETSY', name: 'Etsy Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'EXPE', name: 'Expedia Group Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'BABA', name: 'Alibaba Group Holding Ltd.', sector: 'DISCRETIONARY' },
  { symbol: 'PDD', name: 'PDD Holdings Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'JD', name: 'JD.com Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'NIO', name: 'NIO Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'XPEV', name: 'XPeng Inc.', sector: 'DISCRETIONARY' },
  { symbol: 'LI', name: 'Li Auto Inc.', sector: 'DISCRETIONARY' },

  // ---- Consumer Staples -----------------------------------------------
  { symbol: 'PG', name: 'Procter & Gamble Co.', sector: 'STAPLES' },
  { symbol: 'KO', name: 'Coca-Cola Co.', sector: 'STAPLES' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'STAPLES' },
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'STAPLES' },
  { symbol: 'COST', name: 'Costco Wholesale Corp.', sector: 'STAPLES' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.', sector: 'STAPLES' },
  { symbol: 'PM', name: 'Philip Morris International Inc.', sector: 'STAPLES' },
  { symbol: 'MO', name: 'Altria Group Inc.', sector: 'STAPLES' },
  { symbol: 'CL', name: 'Colgate-Palmolive Co.', sector: 'STAPLES' },
  { symbol: 'TGT', name: 'Target Corp.', sector: 'STAPLES' },
  { symbol: 'MNST', name: 'Monster Beverage Corp.', sector: 'STAPLES' },
  { symbol: 'STZ', name: 'Constellation Brands Inc.', sector: 'STAPLES' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.', sector: 'STAPLES' },
  { symbol: 'KVUE', name: 'Kenvue Inc.', sector: 'STAPLES' },

  // ---- Communication Services -----------------------------------------
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', sector: 'COMMUNICATION' },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'COMMUNICATION' },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'COMMUNICATION' },
  { symbol: 'DIS', name: 'Walt Disney Co.', sector: 'COMMUNICATION' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.', sector: 'COMMUNICATION' },
  { symbol: 'T', name: 'AT&T Inc.', sector: 'COMMUNICATION' },
  { symbol: 'CMCSA', name: 'Comcast Corp.', sector: 'COMMUNICATION' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', sector: 'COMMUNICATION' },
  { symbol: 'CHTR', name: 'Charter Communications Inc.', sector: 'COMMUNICATION' },
  { symbol: 'SPOT', name: 'Spotify Technology S.A.', sector: 'COMMUNICATION' },
  { symbol: 'RDDT', name: 'Reddit Inc.', sector: 'COMMUNICATION' },
  { symbol: 'PINS', name: 'Pinterest Inc.', sector: 'COMMUNICATION' },
  { symbol: 'SNAP', name: 'Snap Inc.', sector: 'COMMUNICATION' },
  { symbol: 'ROKU', name: 'Roku Inc.', sector: 'COMMUNICATION' },
  { symbol: 'TTD', name: 'Trade Desk Inc.', sector: 'COMMUNICATION' },
  { symbol: 'DUOL', name: 'Duolingo Inc.', sector: 'COMMUNICATION' },
  { symbol: 'MTCH', name: 'Match Group Inc.', sector: 'COMMUNICATION' },
  { symbol: 'EA', name: 'Electronic Arts Inc.', sector: 'COMMUNICATION' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software Inc.', sector: 'COMMUNICATION' },
  { symbol: 'LYV', name: 'Live Nation Entertainment Inc.', sector: 'COMMUNICATION' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.', sector: 'COMMUNICATION' },
  { symbol: 'BIDU', name: 'Baidu Inc.', sector: 'COMMUNICATION' },

  // ---- Utilities ------------------------------------------------------
  { symbol: 'NEE', name: 'NextEra Energy Inc.', sector: 'UTILITIES' },
  { symbol: 'DUK', name: 'Duke Energy Corp.', sector: 'UTILITIES' },
  { symbol: 'SO', name: 'Southern Co.', sector: 'UTILITIES' },
  { symbol: 'D', name: 'Dominion Energy Inc.', sector: 'UTILITIES' },
  { symbol: 'AEP', name: 'American Electric Power Co. Inc.', sector: 'UTILITIES' },
  { symbol: 'EXC', name: 'Exelon Corp.', sector: 'UTILITIES' },
  { symbol: 'VST', name: 'Vistra Corp.', sector: 'UTILITIES' },
  { symbol: 'CEG', name: 'Constellation Energy Corp.', sector: 'UTILITIES' },
  { symbol: 'NRG', name: 'NRG Energy Inc.', sector: 'UTILITIES' },
  { symbol: 'TLN', name: 'Talen Energy Corp.', sector: 'UTILITIES' },

  // ---- Materials ------------------------------------------------------
  { symbol: 'LIN', name: 'Linde plc', sector: 'MATERIALS' },
  { symbol: 'APD', name: 'Air Products and Chemicals Inc.', sector: 'MATERIALS' },
  { symbol: 'SHW', name: 'Sherwin-Williams Co.', sector: 'MATERIALS' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc.', sector: 'MATERIALS' },
  { symbol: 'ECL', name: 'Ecolab Inc.', sector: 'MATERIALS' },
  { symbol: 'NEM', name: 'Newmont Corp.', sector: 'MATERIALS' },
  { symbol: 'NUE', name: 'Nucor Corp.', sector: 'MATERIALS' },
  { symbol: 'STLD', name: 'Steel Dynamics Inc.', sector: 'MATERIALS' },
  { symbol: 'CLF', name: 'Cleveland-Cliffs Inc.', sector: 'MATERIALS' },
  { symbol: 'AA', name: 'Alcoa Corp.', sector: 'MATERIALS' },
  { symbol: 'ALB', name: 'Albemarle Corp.', sector: 'MATERIALS' },
  { symbol: 'MP', name: 'MP Materials Corp.', sector: 'MATERIALS' },
  { symbol: 'MOS', name: 'Mosaic Co.', sector: 'MATERIALS' },
  { symbol: 'CF', name: 'CF Industries Holdings Inc.', sector: 'MATERIALS' },
  { symbol: 'VALE', name: 'Vale S.A.', sector: 'MATERIALS' },

  // ---- Real Estate ----------------------------------------------------
  { symbol: 'PLD', name: 'Prologis Inc.', sector: 'REAL_ESTATE' },
  { symbol: 'AMT', name: 'American Tower Corp.', sector: 'REAL_ESTATE' },
  { symbol: 'EQIX', name: 'Equinix Inc.', sector: 'REAL_ESTATE' },
  { symbol: 'CCI', name: 'Crown Castle Inc.', sector: 'REAL_ESTATE' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'REAL_ESTATE' },
  { symbol: 'O', name: 'Realty Income Corp.', sector: 'REAL_ESTATE' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.', sector: 'REAL_ESTATE' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.', sector: 'REAL_ESTATE' },
  { symbol: 'WELL', name: 'Welltower Inc.', sector: 'REAL_ESTATE' },
  { symbol: 'IRM', name: 'Iron Mountain Inc.', sector: 'REAL_ESTATE' },
] as const;

export function stockBySymbol(symbol: string): StockDef | undefined {
  const upper = symbol.trim().toUpperCase();
  return STOCK_UNIVERSE.find((s) => s.symbol === upper);
}
